// <auto-generated />
using System;
using System.Reflection;
using Intersect.Server.Database.GameData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Intersect.Server.Migrations.Sqlite.Game
{
    [DbContext(typeof(SqliteGameContext))]
    [Migration("20240521000000_PlaceableItems")]
    partial class PlaceableItems
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            var snapshot = new SqliteGameContextModelSnapshot();
            typeof(SqliteGameContextModelSnapshot)
                .GetMethod("BuildModel", BindingFlags.Instance | BindingFlags.NonPublic)!
                .Invoke(snapshot, new object[] { modelBuilder });
#pragma warning restore 612, 618
        }
    }
}
